name: Xaml Styler Minimal

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  xaml-styler:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install XAML Styler 
      run: dotnet tool update --global XamlStyler.Console
    - name: Verify XAML Styling
      run: xstyler -r -l Minimal -c Settings.XamlStyler -d "." --passive
